name: Release

on:
  push:
    tags:
      - "*"
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    name: Build and push Docker release for latest tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get latest tag
        id: tag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
        with:
          fallback: v1.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push to Docker Hub
        uses: docker/build-push-action@v4
        with:
          platforms: linux/amd64,linux/arm64,linux/arm/v6,linux/arm/v7
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/acme-tiny-docker:${{ steps.tag.outputs.tag }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
